# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sentinel_pb2 as sentinel__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sentinel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentinelStub(object):
    """Sentinel is the main service for producing and consuming messages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Produce = channel.unary_unary(
                '/sentinel.Sentinel/Produce',
                request_serializer=sentinel__pb2.ProduceRequest.SerializeToString,
                response_deserializer=sentinel__pb2.ProduceResponse.FromString,
                _registered_method=True)
        self.Consume = channel.unary_stream(
                '/sentinel.Sentinel/Consume',
                request_serializer=sentinel__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=sentinel__pb2.Record.FromString,
                _registered_method=True)
        self.FetchMetadata = channel.unary_unary(
                '/sentinel.Sentinel/FetchMetadata',
                request_serializer=sentinel__pb2.MetadataRequest.SerializeToString,
                response_deserializer=sentinel__pb2.MetadataResponse.FromString,
                _registered_method=True)


class SentinelServicer(object):
    """Sentinel is the main service for producing and consuming messages.
    """

    def Produce(self, request, context):
        """Produce sends messages to a topic partition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Consume streams messages from a topic partition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchMetadata(self, request, context):
        """FetchMetadata returns cluster and topic metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentinelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Produce': grpc.unary_unary_rpc_method_handler(
                    servicer.Produce,
                    request_deserializer=sentinel__pb2.ProduceRequest.FromString,
                    response_serializer=sentinel__pb2.ProduceResponse.SerializeToString,
            ),
            'Consume': grpc.unary_stream_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=sentinel__pb2.ConsumeRequest.FromString,
                    response_serializer=sentinel__pb2.Record.SerializeToString,
            ),
            'FetchMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchMetadata,
                    request_deserializer=sentinel__pb2.MetadataRequest.FromString,
                    response_serializer=sentinel__pb2.MetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.Sentinel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.Sentinel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sentinel(object):
    """Sentinel is the main service for producing and consuming messages.
    """

    @staticmethod
    def Produce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.Sentinel/Produce',
            sentinel__pb2.ProduceRequest.SerializeToString,
            sentinel__pb2.ProduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sentinel.Sentinel/Consume',
            sentinel__pb2.ConsumeRequest.SerializeToString,
            sentinel__pb2.Record.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.Sentinel/FetchMetadata',
            sentinel__pb2.MetadataRequest.SerializeToString,
            sentinel__pb2.MetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
